# Copyright 2026 the-monolith
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DESCRIPTION="Hand-authored rootfs helpers for The Monolith (net/router/console, which, guestbook CGI, advisory banner, prompt)"
HOMEPAGE="https://github.com/tuckermclean/linux-live-iso-factory"

# No upstream source — every file here is hand-authored in-tree under
# FILESDIR (previously configs/rootfs-overlay/ + ad-hoc `install` lines in
# scripts/build-rootfs.sh; see git history). Nothing to fetch or unpack, so
# S is pinned to WORKDIR — EAPI 8's default S="${WORKDIR}/${P}" would not
# exist since there is no SRC_URI to create it.
S="${WORKDIR}"

# In-house scripts; no single upstream license file to point to.
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"

src_install() {
	# /usr/bin — monolith-net (SP1 ISA NIC probe helper) and the POSIX-sh
	# `which` (GNU sys-apps/which doesn't build against musl; busybox isn't
	# in this rootfs). Unit-tested standalone: scripts/tests/monolith-net.test.sh.
	exeinto /usr/bin
	doexe "${FILESDIR}/monolith-net"
	doexe "${FILESDIR}/which"
	# startx (SP-GUI G2): brings up Xfbdev (built-in fonts) + a terminal (st) on
	# the framebuffer. Hand-authored → owned here so it isn't an unowned rootfs
	# file (attestation Pillar 4). See files/startx.
	doexe "${FILESDIR}/startx"
	# monolith (Monolith UX Pass, Task 1): the front door — lists the helpers
	# and curated tools below instead of leaving them to tribal knowledge.
	# Unit-tested standalone: scripts/tests/monolith.test.sh.
	doexe "${FILESDIR}/monolith"

	# /usr/sbin — monolith-router (SP2/SP3 NAT + dnsmasq DHCP/DNS helper,
	# unit-tested: scripts/tests/monolith-router.test.sh), monolith-console
	# (lazy auto-login shell, see /etc/inittab), and the advisory-check
	# fetcher (runs from /etc/init.d/S50advisory).
	exeinto /usr/sbin
	doexe "${FILESDIR}/monolith-router"
	doexe "${FILESDIR}/monolith-console"
	doexe "${FILESDIR}/monolith-advisory-check"
	# monolith-time (UX Pass Task 2, the clock landmine): sets the clock
	# from an HTTP Date header, and monolith-time-check, the gate that
	# decides WHEN it's allowed to run (demonstrated ignorance only — see
	# the INVARIANT in monolith-time-check). Runs from
	# /etc/init.d/S45monolith-time. Unit-tested standalone:
	# scripts/tests/monolith-time.test.sh.
	doexe "${FILESDIR}/monolith-time"
	doexe "${FILESDIR}/monolith-time-check"
	# monolith-persist (UX Pass Task 3, persist continuity): the
	# mkfs.ext4 -L MONOLITH_PERSIST liturgy as a script, with one
	# confirmation naming the device + its current contents' fate, and
	# an optional --swap N swapfile. Manual tool — nothing runs it
	# automatically. Unit-tested standalone:
	# scripts/tests/monolith-persist.test.sh.
	doexe "${FILESDIR}/monolith-persist"

	# /usr/lib/cgi-bin — SP5 P4 LAMP-invariant guestbook fixture (perl +
	# CGI.pm + the sqlite3 CLI). Ships executable; perl reads its own
	# shebang. See scripts/boot-test.py smoke_guestbook.
	exeinto /usr/lib/cgi-bin
	doexe "${FILESDIR}/guestbook.cgi"

	# /usr/share/monolith — curated topic text for `monolith help <topic>` /
	# `monolith tools` (Task 1). Plain text, cat/pager'd, never generated.
	insinto /usr/share/monolith
	doins "${FILESDIR}/topics/"*.txt

	# /etc/profile.d — sourced by /etc/profile, not executed directly.
	#
	# ORDERING CONTRACT (Monolith UX Pass Task 6, hint hygiene): /etc/profile
	# sources /etc/profile.d/*.sh in glob (ASCII lexical) order, and every
	# login-hint snippet in this rootfs obeys ONE contract for that order:
	#
	#   1. STATUS lines first  — 20-persist.sh, then 30-clock-hint.sh
	#   2. ACTIONABLE hints second, security before convenience —
	#      40-advisory.sh, then 50-dropbear-hint.sh (the latter is
	#      generated by scripts/build-rootfs.sh, not doins'd here, but
	#      obeys the same numeric slot)
	#
	# Budget: ≤10 lines of output on a clean boot (persist present, clock
	# fine, no advisory, dropbear not running).
	#
	# /run-flag policy, per snippet (the annoyance-vs-value call for
	# hints that could repeat every login):
	#   - persist status: EVERY login, no flag — cheap (one mount-table
	#     read), and the answer can change between logins.
	#   - clock-ignorance hint: only while /run/monolith-clock-ignorant
	#     exists (the demonstrated-ignorance case) — silent otherwise,
	#     including a correct pre-NTP clock.
	#   - advisory banner: only while /run/monolith-advisory exists.
	#   - dropbear hint: EVERY login, ON PURPOSE, no flag — it is a
	#     security-posture reminder (sshd is present but off) that is
	#     meant to repeat deliberately, not a one-shot tip. Do not add a
	#     once-guard to it.
	insinto /etc/profile.d
	# 40-advisory.sh (renamed from monolith-advisory.sh in Task 6):
	# ACTIONABLE-group, security before convenience — see the ordering
	# contract above.
	doins "${FILESDIR}/40-advisory.sh"
	# 30-clock-hint.sh (renamed from monolith-time-hint.sh in Task 6):
	# STATUS-group, clock-ignorance case only — see the ordering contract
	# above.
	doins "${FILESDIR}/30-clock-hint.sh"
	# 20-persist.sh (UX Pass Task 3): one-line persist status at login
	# ("persist: mounted (N MB free)" / "persist: none ..."). The
	# history-reliability half lives in 50-persist-history.bash below
	# (bashrc.d, not profile.d — see that file's header for why). Unit-
	# tested standalone: scripts/tests/monolith-persist-profile.test.sh.
	doins "${FILESDIR}/20-persist.sh"

	# /etc/bash/bashrc.d — sourced from bash's bashrc.d chain, AFTER the
	# stock /etc/bash/bashrc has done its own setup (runs last: prepends
	# the dark-grey ■ after 10-gentoo-color.bash sets PS1; wires up
	# persist's incremental history-append without risking Gentoo's stock
	# bashrc clobbering it). Unit-tested standalone:
	# scripts/tests/monolith-persist-bashrc.test.sh.
	insinto /etc/bash/bashrc.d
	doins "${FILESDIR}/99-monolith-square.bash"
	doins "${FILESDIR}/50-persist-history.bash"
	# 60-monolith-cnf.bash (UX Pass Task 5): command_not_found_handle,
	# pointing a miss at `monolith tools` instead of bash's bare
	# "command not found". bashrc.d, not profile.d — see the file's own
	# header for why (a function definition, not a login side effect).
	doins "${FILESDIR}/60-monolith-cnf.bash"
}
