# Disable Position Independent Executable (PIE) generation
#
# Some packages have issues with PIE when statically linking,
# especially on i486 with musl.

CFLAGS="${CFLAGS} -no-pie -fno-pie"
CXXFLAGS="${CXXFLAGS} -no-pie -fno-pie"
LDFLAGS="${LDFLAGS} -no-pie"
