#!/bin/bash
#
# update-versions.sh - Manage package version pinning
#
# Commands:
#   check    - Show available updates vs pinned versions
#   update   - Query eix and write new versions.lock
#   validate - Check versions.lock format

set -e

CONFIGS_DIR="${CONFIGS_DIR:-/configs}"
PORTAGE_DIR="${CONFIGS_DIR}/portage"
WORLD_FILE="${PORTAGE_DIR}/world"
VERSIONS_FILE="${PORTAGE_DIR}/versions.lock"

usage() {
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "  check     Show available updates vs pinned versions"
    echo "  update    Query eix and write new versions.lock"
    echo "  validate  Check versions.lock format"
    exit 1
}

# Ensure eix database is current
ensure_eix() {
    if ! command -v eix &>/dev/null; then
        echo "ERROR: eix not found. Install app-portage/eix"
        exit 1
    fi

    # Update eix database if needed
    if [ ! -f /var/cache/eix/portage.eix ] || \
       [ /var/db/repos/gentoo -nt /var/cache/eix/portage.eix ]; then
        echo "Updating eix database..."
        eix-update
    fi
}

# Get best available version for a package
get_best_version() {
    local pkg="$1"
    # Use eix to find the best visible version
    eix --pure-packages --format '<bestversion:VERSION>' --exact "${pkg}" 2>/dev/null | head -1
}

# Get slot for a package version
get_slot() {
    local pkg="$1"
    eix --pure-packages --format '<bestversion:SLOT>' --exact "${pkg}" 2>/dev/null | head -1
}

# Read world file
read_world() {
    if [ ! -f "${WORLD_FILE}" ]; then
        echo "ERROR: World file not found: ${WORLD_FILE}"
        exit 1
    fi
    grep -v '^#' "${WORLD_FILE}" | grep -v '^$'
}

# Command: check
cmd_check() {
    ensure_eix

    echo "==> Checking package versions"
    echo ""
    printf "%-35s %-15s %-15s\n" "Package" "Pinned" "Available"
    printf "%-35s %-15s %-15s\n" "-------" "------" "---------"

    while read -r pkg; do
        [ -z "${pkg}" ] && continue

        # Get pinned version
        PINNED=""
        if [ -f "${VERSIONS_FILE}" ]; then
            PINNED=$(grep "^${pkg}:" "${VERSIONS_FILE}" 2>/dev/null | cut -d: -f2 | head -1)
        fi
        [ -z "${PINNED}" ] && PINNED="(unpinned)"

        # Get available version
        AVAILABLE=$(get_best_version "${pkg}")
        [ -z "${AVAILABLE}" ] && AVAILABLE="(not found)"

        # Mark if update available
        if [ "${PINNED}" != "(unpinned)" ] && [ "${PINNED}" != "${AVAILABLE}" ]; then
            MARKER="*"
        else
            MARKER=""
        fi

        printf "%-35s %-15s %-15s %s\n" "${pkg}" "${PINNED}" "${AVAILABLE}" "${MARKER}"

    done < <(read_world)

    echo ""
    echo "* = update available"
}

# Command: update
cmd_update() {
    ensure_eix

    echo "==> Updating versions.lock"

    # Create new versions file
    TMPFILE=$(mktemp)

    cat > "${TMPFILE}" << 'EOF'
# Pinned package versions for reproducible builds
#
# Format: category/package:version:slot
# Generated by: update-versions.sh update
#
EOF
    echo "# Updated: $(date -Iseconds)" >> "${TMPFILE}"
    echo "" >> "${TMPFILE}"

    while read -r pkg; do
        [ -z "${pkg}" ] && continue

        VERSION=$(get_best_version "${pkg}")
        SLOT=$(get_slot "${pkg}")

        if [ -n "${VERSION}" ]; then
            echo "${pkg}:${VERSION}:${SLOT:-0}" >> "${TMPFILE}"
            echo "  ${pkg}:${VERSION}:${SLOT:-0}"
        else
            echo "  WARNING: ${pkg} not found in portage tree"
        fi

    done < <(read_world)

    # Replace old versions file
    mv "${TMPFILE}" "${VERSIONS_FILE}"

    echo ""
    echo "==> Wrote ${VERSIONS_FILE}"
}

# Command: validate
cmd_validate() {
    if [ ! -f "${VERSIONS_FILE}" ]; then
        echo "ERROR: Versions file not found: ${VERSIONS_FILE}"
        exit 1
    fi

    echo "==> Validating versions.lock format"

    ERRORS=0
    LINE_NUM=0

    while IFS= read -r line; do
        ((LINE_NUM++))

        # Skip comments and blank lines
        [[ "${line}" =~ ^# ]] && continue
        [[ -z "${line}" ]] && continue

        # Validate format: category/package:version:slot
        if ! [[ "${line}" =~ ^[a-z0-9-]+/[a-z0-9_+-]+:[0-9a-zA-Z._-]+:[0-9]+$ ]]; then
            echo "  Line ${LINE_NUM}: Invalid format: ${line}"
            ((ERRORS++))
        fi

    done < "${VERSIONS_FILE}"

    if [ ${ERRORS} -eq 0 ]; then
        echo "  OK: Format is valid"
        exit 0
    else
        echo ""
        echo "  ERRORS: ${ERRORS} invalid lines"
        exit 1
    fi
}

# Main
case "${1:-}" in
    check)
        cmd_check
        ;;
    update)
        cmd_update
        ;;
    validate)
        cmd_validate
        ;;
    *)
        usage
        ;;
esac
